dqawse – quadpack
dqawse Subroutine
135 statements
Source File
public subroutine dqawse(f, a, b, Alfa, Beta, Integr, Epsabs, Epsrel, Limit, Result, Abserr, Neval, Ier, Alist, Blist, Rlist, Elist, Iord, Last)
same as dqaws but provides more information and control
the routine calculates an approximation result to a given definite integral i = integral of f*w over (a,b), (where w shows a singular behaviour at the end points, see parameter integr). hopefully satisfying following claim for accuracy abs(i-result)<=max(epsabs,epsrel*abs(i)).
History
QUADPACK: date written 800101, revision date 830518 (yymmdd)
Arguments
Type Intent Optional Attributes Name
procedure(func) :: f
function subprogram defining the integrand function f(x).
real(kind=wp), intent(in) :: a
lower limit of integration
real(kind=wp), intent(in) :: b
upper limit of integration, b>a. if b<=a, the routine will end with ier = 6.
real(kind=wp), intent(in) :: Alfa
parameter in the weight function, alfa>(-1) if alfa<=(-1), the routine will end with ier = 6.
real(kind=wp), intent(in) :: Beta
parameter in the weight function, beta>(-1) if beta<=(-1), the routine will end with ier = 6.
integer, intent(in) :: Integr
indicates which weight function is to be used:
= 1 (x-a)**alfa*(b-x)**beta
= 2 (x-a)**alfa*(b-x)**beta*log(x-a)
= 3 (x-a)**alfa*(b-x)**beta*log(b-x)
= 4 (x-a)**alfa*(b-x)**beta*log(x-a)*log(b-x)
if integr<1 or integr>4, the routine will end with ier = 6.
real(kind=wp), intent(in) :: Epsabs
absolute accuracy requested
real(kind=wp), intent(in) :: Epsrel
relative accuracy requested. if epsabs<=0 and epsrel<max(50*rel.mach.acc.,0.5e-28), the routine will end with ier = 6.
integer, intent(in) :: Limit
gives an upper bound on the number of subintervals in the partition of (a,b), limit>=2 if limit<2, the routine will end with ier = 6.
real(kind=wp), intent(out) :: Result
approximation to the integral
real(kind=wp), intent(out) :: Abserr
estimate of the modulus of the absolute error, which should equal or exceed abs(i-result)
integer, intent(out) :: Neval
number of integrand evaluations
integer, intent(out) :: Ier
ier = 0 normal and reliable termination of the routine. it is assumed that the requested accuracy has been achieved.
ier>0 abnormal termination of the routine the estimates for the integral and error are less reliable. it is assumed that the requested accuracy has not been achieved. error messages
ier = 1 maximum number of subdivisions allowed has been achieved. one can allow more subdivisions by increasing the value of limit. however, if this yields no improvement, it is advised to analyze the integrand in order to determine the integration difficulties which prevent the requested tolerance from being achieved. in case of a jump discontinuity or a local singularity of algebraico-logarithmic type at one or more interior points of the integration range, one should proceed by splitting up the interval at these points and calling the integrator on the subranges.
ier = 2 the occurrence of roundoff error is detected, which prevents the requested tolerance from being achieved.
ier = 3 extremely bad integrand behaviour occurs at some points of the integration interval.
ier = 6 the input is invalid, because b<=a or alfa<=(-1) or beta<=(-1), or integr<1 or integr>4, or epsabs<=0 and epsrel<max(50*rel.mach.acc.,0.5e-28), or limit<2. result, abserr, neval, rlist(1), elist(1), iord(1) and last are set to zero. alist(1) and blist(1) are set to a and b respectively.
real(kind=wp), intent(out) :: Alist(Limit)
vector of dimension at least limit, the first last elements of which are the left end points of the subintervals in the partition of the given integration range (a,b)
real(kind=wp), intent(out) :: Blist(Limit)
vector of dimension at least limit, the first last elements of which are the right end points of the subintervals in the partition of the given integration range (a,b)
real(kind=wp), intent(out) :: Rlist(Limit)
vector of dimension at least limit,the first last elements of which are the integral approximations on the subintervals
real(kind=wp), intent(out) :: Elist(Limit)
vector of dimension at least limit, the first last elements of which are the moduli of the absolute error estimates on the subintervals
integer, intent(out) :: Iord(Limit)
vector of dimension at least limit, the first k of which are pointers to the error estimates over the subintervals, so that elist(iord(1)), ..., elist(iord(k)) with k = last if last<=(limit/2+2), and k = limit+1-last otherwise form a decreasing sequence
integer, intent(out) :: Last
number of subintervals actually produced in the subdivision process
Calls
Called by
Contents
None
Call graph
dqawse calls dqmomo, dqc25s
dqc25s calls dqk15w, dqcheb
dqaws calls dqawse