dqc25s – quadpack
dqc25s Subroutine
187 statements
Source File
public subroutine dqc25s(f, a, b, Bl, Br, Alfa, Beta, Ri, Rj, Rg, Rh, Result, Abserr, Resasc, Integr, Nev)
25-point clenshaw-curtis integration
to compute i = integral of f*w over (bl,br), with error estimate, where the weight function w has a singular behaviour of algebraico-logarithmic type at the points a and/or b. (bl,br) is a part of (a,b).
History
QUADPACK: date written 810101, revision date 830518 (yymmdd)
Arguments
Type Intent Optional Attributes Name
procedure(func) :: f
function subprogram defining the integrand f(x).
real(kind=wp), intent(in) :: a
left end point of the original interval
real(kind=wp), intent(in) :: b
right end point of the original interval, b>a
real(kind=wp), intent(in) :: Bl
lower limit of integration, bl>=a
real(kind=wp), intent(in) :: Br
upper limit of integration, br<=b
real(kind=wp), intent(in) :: Alfa
parameter in the weight function
real(kind=wp), intent(in) :: Beta
parameter in the weight function
real(kind=wp), intent(in) :: Ri(25)
modified chebyshev moments for the application of the generalized clenshaw-curtis method (computed in subroutine dqmomo)
real(kind=wp), intent(in) :: Rj(25)
modified chebyshev moments for the application of the generalized clenshaw-curtis method (computed in subroutine dqmomo)
real(kind=wp), intent(in) :: Rg(25)
modified chebyshev moments for the application of the generalized clenshaw-curtis method (computed in subroutine dqmomo)
real(kind=wp), intent(in) :: Rh(25)
modified chebyshev moments for the application of the generalized clenshaw-curtis method (computed in subroutine dqmomo)
real(kind=wp), intent(out) :: Result
approximation to the integral result is computed by using a generalized clenshaw-curtis method if b1 = a or br = b. in all other cases the 15-point kronrod rule is applied, obtained by optimal addition of abscissae to the 7-point gauss rule.
real(kind=wp), intent(out) :: Abserr
estimate of the modulus of the absolute error, which should equal or exceed abs(i-result)
real(kind=wp), intent(out) :: Resasc
approximation to the integral of abs(f*w-i/(b-a))
integer, intent(in) :: Integr
which determines the weight function * = 1 w(x) = (x-a)**alfa*(b-x)**beta * = 2 w(x) = (x-a)**alfa*(b-x)**beta*log(x-a) * = 3 w(x) = (x-a)**alfa*(b-x)**beta*log(b-x) * = 4 w(x) = (x-a)**alfa*(b-x)**beta*log(x-a)*log(b-x)
integer, intent(out) :: Nev
number of integrand evaluations
Calls
Called by
Contents
None
Call graph
dqc25s calls dqcheb, dqk15w
dqawse calls dqc25s
dqaws calls dqawse