dqk15w – quadpack
dqk15w Subroutine
74 statements
Source File
public subroutine dqk15w(f, w, p1, p2, p3, p4, Kp, a, b, Result, Abserr, Resabs, Resasc)
estimate 1D integral with special singular weight functions using a 15 point gauss-kronrod quadrature rule
to compute i = integral of f*w over (a,b), with error estimate j = integral of abs(f*w) over (a,b)
History
QUADPACK: date written 810101, revision date 830518 (yymmdd).
Arguments
Type Intent Optional Attributes Name
procedure(func) :: f
function subprogram defining the integrand function f(x).
procedure(weight_func) :: w
function subprogram defining the integrand weight function w(x).
real(kind=wp), intent(in) :: p1
parameter in the weight function
real(kind=wp), intent(in) :: p2
parameter in the weight function
real(kind=wp), intent(in) :: p3
parameter in the weight function
real(kind=wp), intent(in) :: p4
parameter in the weight function
integer, intent(in) :: Kp
key for indicating the type of weight function
real(kind=wp), intent(in) :: a
lower limit of integration
real(kind=wp), intent(in) :: b
upper limit of integration
real(kind=wp), intent(out) :: Result
approximation to the integral i result is computed by applying the 15-point kronrod rule (resk) obtained by optimal addition of abscissae to the 7-point gauss rule (resg).
real(kind=wp), intent(out) :: Abserr
estimate of the modulus of the absolute error, which should equal or exceed abs(i-result)
real(kind=wp), intent(out) :: Resabs
approximation to the integral of abs(f)
real(kind=wp), intent(out) :: Resasc
approximation to the integral of abs(f-i/(b-a))
Called by
Contents
None
Call graph
dqc25f calls dqk15w
dqc25s calls dqk15w
dqc25c calls dqk15w
dqawce calls dqc25c
dqawoe calls dqc25f
dqawse calls dqc25s
dqawfe calls dqawoe
dqawc calls dqawce
dqawo calls dqawoe
dqaws calls dqawse
dqawf calls dqawfe